"""Living architecture docs generated from the model (deterministic / idempotent).

Intentionally excludes wall-clock timestamps so regeneration is byte-identical when
the model is unchanged (verification relies on this). Produces architecture.md with
a Mermaid layer diagram and a component catalog.
"""

from __future__ import annotations

from collections import defaultdict
from typing import Dict, List, Set, Tuple

from archsteer.engine.model import ArchitectureModel


def _layer_edges(model: ArchitectureModel) -> Set[Tuple[str, str]]:
    edges: Set[Tuple[str, str]] = set()
    for src, dst in model.internal_edges():
        sl = model.components[src].layer or "unassigned"
        dl = model.components[dst].layer or "unassigned"
        if sl != dl:
            edges.add((sl, dl))
    return edges


def _mermaid(model: ArchitectureModel) -> str:
    edges = sorted(_layer_edges(model))
    layers = sorted(model.get_layers() | {"unassigned"})
    lines = ["```mermaid", "graph LR"]
    if not edges:
        for layer in layers:
            lines.append(f"    {layer}[{layer}]")
    for sl, dl in edges:
        lines.append(f"    {sl}[{sl}] --> {dl}[{dl}]")
    lines.append("```")
    return "\n".join(lines)


def render_architecture_md(model: ArchitectureModel) -> str:
    layer_counts: Dict[str, int] = defaultdict(int)
    for comp in model.components.values():
        layer_counts[comp.layer or "unassigned"] += 1

    ext_deps = sorted(model.get_all_external_dependencies())
    stores = sorted(model.get_all_data_stores())

    out: List[str] = [
        f"# Architecture — {model.repo_name}",
        "",
        "> Auto-generated by ArchSteer from source. Do not edit by hand; run `archsteer docs`.",
        "",
        "## Overview",
        f"- **Components:** {len(model.components)}",
        f"- **Layers:** {', '.join(sorted(model.get_layers())) or '—'}",
        f"- **Data stores:** {', '.join(stores) or '—'}",
        f"- **External call sites:** {sum(len(c.external_calls) for c in model.components.values())}",
        "",
        "## Layer map",
        _mermaid(model),
        "",
        "## Components by layer",
    ]
    for layer in sorted(layer_counts):
        out.append(f"- **{layer}** — {layer_counts[layer]} component(s)")
    out += ["", "## Component catalog", "", "| Component | Layer | Exports | Data access | External |", "|---|---|---|---|---|"]
    for path in sorted(model.components):
        c = model.components[path]
        exports = ", ".join(c.exported_apis[:4]) or "—"
        da = ", ".join(sorted({d.entity for d in c.data_access})) or "—"
        ext = str(len(c.external_calls)) if c.external_calls else "—"
        out.append(f"| `{path}` | {c.layer or '—'} | {exports} | {da} | {ext} |")
    out.append("")
    return "\n".join(out)
